### ISSUE TITLE
MinimumFileAgeDays Discrepancy

### ISSUE THREAD

**Issue by dyehya** [MicrosoftDocs/windows-powershell-docs#2065] opened 2020-07-29 15:48 UTC
This is conflicting information regarding MinimumFileAgeDays which should be rectified. I assume the correct information is based on the created time especially since dedup supports files in use if enabled for the volume.

Per this site: [https://docs.microsoft.com/en-us/windows-server/storage/data-deduplication/advanced-settings](https://docs.microsoft.com/en-us/windows-server/storage/data-deduplication/advanced-settings)

> The Default and HyperV usage types set this value to 3 to maximize performance on hot or recently created files.

While on this page it says:

> -MinimumFileAgeDays
> Specifies a number of days. The deduplication engine optimizes files that users have not accessed in the number of days that you specify. If the last access time is not available, then the deduplication engine uses the last modified time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53037750-a381-fc0c-b36f-8a6ab2e148bf
* Version Independent ID: f417a83e-dbea-2d77-b753-23e665546b8b
* Content: [Set-DedupVolume (deduplication)](https://docs.microsoft.com/en-us/powershell/module/deduplication/set-dedupvolume?view=win10-ps)
* Content Source: [docset/windows/deduplication/Set-DedupVolume.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/deduplication/Set-DedupVolume.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment] 2020-09-19 12:09
@dyehya Hello,

Thank you for trying to make MicrosoftDocs a better place. 

The link that you have provided says that the default value for `Default` and `Hyper-V` usage types is 3. You can still override this setting by specifying the *MinimumFileAgeDays* parameter. I do not see any conflict between the two. Probably it is useful to have this information in the parameter description as well.

**Comment by dyehya** [comment] 2020-09-23 22:53
Thank you both for the updates. 

Can we get confirmation from the Product Group/Team on whether or not the deduplication engine uses the last access time or last modified time at all?
The updated documentation now makes it sound like it ONLY goes by created date but I do not believe the Deduplication Engine is exclusively using the created date.

**Comment by e0i** [comment] 2020-09-24 15:50
Hello, @dyehya It seems that your follow-up question can best be answered via [PowerShell Community Links](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Since the associated PR has been merged and the content has been updated according to your feedback, the issue is being closed because the issues section of this repository is used to address content related issues. 

Thank you.

**Comment by dyehya** [comment] 2020-09-25 01:15
I am concerned regarding the content because it still doesn't add up is my point.

> The Default and HyperV usage types set this value to 3 to maximize performance **_on hot_** or recently created files. You may want to modify this if you want Data Deduplication to be more aggressive or if you do not care about the extra latency associated with deduplication.

Logic dictates that if:
> MinimumFileAgeDays | Number of days after the file is created before the file is considered to be in-policy for optimization.

Then how can the documentation state that it is the number of days after the file is created only when it does use the access time if it is available. The documentation is wrong... just because you updated it doesn't make it consistent or correct. I suggested the Product Group because they would be the definitive expert on the system vs a user like myself but the logic issue is obvious here.

Also, it specifically mentions if the data is **_hot_** OR recently created. Therefore it will not optimize if it is was recently accessed or modified (depending on how the engine works).

I know how to work Powershell. I am not asking for support. I am asking you to correct the documentation and the relevant pages so they are consistent _and_ correct.

**Comment by dyehya** [comment] 2020-09-25 22:06
I do want to also clarify that I do not think documenting that it only works based on the created date was the correct "Correction" to the documentation in case that was not clear above because the dedup engine will not dedup if the data has been accessed or modified recently which is the intended behavior and the documentation should reflect this in all places.

**Comment by scanum** [comment] 2022-11-07 06:01
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support

**Closed by scanum** 2022-11-07 06:01 UTC
Labels: product-question, area-hyper-v
