### ISSUE TITLE
Update-Help fails to update the help for the Defender PowerShell Module

### ISSUE THREAD

**Issue by rgsteele** [MicrosoftDocs/windows-powershell-docs#2188] opened 2020-10-31 23:35 UTC
When I run Update-Help on my system, it fails to update the help for the Windows Defender PowerShell module.

Running `(get-module ConfigDefender).HelpInfoURI` outputs the following URL:

`https://go.microsoft.com/fwlink/?linkid=390762`

This URL redirects to `https://download.microsoft.com/download/8/F/F/8FFB50FC-6D78-4945-B977-92FF2BF975C9/`, which is a 404 Not Found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f5b4eae-d474-2bb1-b388-543216b011cc
* Version Independent ID: 10fb6781-ff32-e3d6-3ea7-8dadb252eb30
* Content: [Defender Module](https://docs.microsoft.com/en-us/powershell/module/defender/?view=win10-ps)
* Content Source: [docset/windows/defender/Defender.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/defender/Defender.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

**Comment by sdwheeler** [comment] 2021-04-06 15:33
These are known issues that have already been reported many times. We are in the process of fixing these issues but it will be a few months before we can implement the final fix. The **ConfigDefender** module is a known bug that will be fixed in the next release of Windows. But there will not be a fix for older versions of Windows. It is an invalid module that can be deleted from your system.

The 404 behavior is expected and by design. The URL endpoint is valid. It points to the folder containing the updateable help for the **Defender** module, but the folder is not browsable, thus the 404.

**Closed by sdwheeler** 2021-04-06 15:33 UTC
