### ISSUE TITLE
Wrong value for DisableArchiveScanning

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-powershell-docs#518] opened 2019-01-02 14:21 UTC
"DisableArchiveScanning" should be either 0 or $False to make Windows Defender not scanning archives.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbad993c-9f2b-9f51-6438-b56cd913ba1b
* Version Independent ID: cc8d93f2-8837-4169-0fc7-167d0ffca777
* Content: [Set-MpPreference (defender)](https://docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=win10-ps)
* Content Source: [docset/windows/defender/set-mppreference.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/defender/set-mppreference.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by sowjanya365** [comment] 2019-05-21 05:24
Hi @LuigiBruno 

Thank you for reaching out!

If we specify either 0 or $False or not specified, Windows Defender scans archive files.

If we specify either 1 or $True, Windows Defender stops scanning the archive files.

Hope this clarifies your query. Kindly confirm. Thank you.

**Comment by LuigiBruno** [comment] 2019-05-21 10:26
Hi @sowjanya365.
Thank you.

**Comment by e0i** [comment] 2019-05-24 15:43
@LuigiBruno 

This issue has already been addressed with the following commit.

[[51ccac0] Update set-mppreference.md ](https://github.com/MicrosoftDocs/windows-powershell-docs/commit/51ccac0bef741c05d870b18ec7df995cd1e08f6d)

The issue is thus being marked as resolved.

Thank you for your feedback and taking the time to follow-up.

**Comment by e0i** [comment] 2019-05-24 15:43
@officedocsbot close

**Comment by LuigiBruno** [comment] 2019-06-26 15:16
> @LuigiBruno
> This issue has already been addressed with the following commit.
> [51ccac0] Update set-mppreference.md 
> The issue is thus being marked as resolved.
> Thank you for your feedback and taking the time to follow-up.

Thanks @e0i.

**Comment by spazmodius** [comment] 2019-07-24 00:42
So, when will these updates be reflected on `docs.microsoft.com`?

**Comment by LuigiBruno** [comment] 2019-09-06 20:57
> So, when will these updates be reflected on docs.microsoft.com?

I think the Microsoft Docs page has been updated.

**Comment by e0i** [comment] 2020-05-06 20:16
Confirmed as updated. Thank you.

**Closed by e0i** 2020-05-06 20:16 UTC
