### ISSUE TITLE
Should list the common error cases here.

### ISSUE THREAD

**Issue by chendrixson** [MicrosoftDocs/windows-powershell-docs#1032] opened 2019-05-01 00:16 UTC
Package in use, missing framework, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b59ed2d-1535-135c-bdaf-95dd93a3ef6b
* Version Independent ID: 6dcca508-5e35-5cb4-942b-22a20dbb1a4d
* Content: [Add-AppxPackage (appx)](https://docs.microsoft.com/en-us/powershell/module/appx/add-appxpackage?view=win10-ps)
* Content Source: [docset/windows/appx/add-appxpackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appx/add-appxpackage.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment] 2019-05-03 01:39
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-05-03 01:44
@chendrixson 

The issue is being routed to Windows PowerShell writing team for investigation. You'll be notified with relevant updates as content gets updated.

Thank you for providing feedback.

**Comment by e0i** [comment] 2019-05-27 18:43
@chendrixson We are working on a PR to address this issue. Thanks.

**Comment by VLG17** [comment] 2019-07-02 09:15
@chendrixson although i fully understand your concern, i personally find it really difficult to address these "common errors", because there is no silver bullet solution for errors like:

**_"Deployment failed with HRESULT: 0x80073D02, The package could not be installed because resources it modifies are currently in use."

"Deployment failed with HRESULT: 0x80073D06, The package could not be installed because a higher version of this package is already installed."_**

There are situations where housekeeping  (deleting rogue objects referenced in the errors) helped. There were cases where a fresh install of the OS, installing missing modules/components or stopping a process (app) solved the issue.

Given all the variables and different methods of isolating and solving such an issue, I would advise to contact [Microsoft Store Support](https://support.microsoft.com/en-us/help/28808) to get these errors fixed.

**Comment by e0i** [comment] 2019-07-02 13:13
Hello @chendrixson ,

We are closing this issue since your question seems to be answered. Feel free to re-open this issue if you still experience problems.

Thanks.

**Comment by e0i** [comment] 2019-07-02 13:13
@officedocsbot close

**Closed by e0i** 2019-07-02 13:13 UTC
