### ISSUE TITLE
Set-AssignedAccess Not Clear on Multiple Users

### ISSUE THREAD

**Issue by danieldjewell** [MicrosoftDocs/windows-powershell-docs#429] opened 2018-10-24 18:52 UTC
Please see #428  as well. 

If I'm reading the definition of Set-AssignedAccess correctly (AssignedAccess.psm1::191 // v1.0 / Module AssignedAccess), it would _appear_ that it's not possible to have **multiple** users with assigned access as the function itself deletes any assigned access for other users before processing the new request (AssignedAccess.psm1::303). 

The documentation does not reflect that only one user can have assigned access at a time by the design of v1.0 of the AssignedAccess module. 

Further, if I'm reading the module code correctly, between ::295 and ::312, the Set-AssignedAccess function will **overwrite** any existing assigned access **without prompting the user** and **regardless of any common flags (e.g. -Confirm)**. The only warnings to the user that assigned access was removed is a message written to **verbose output**. 

As noted in #428, I could not locate a space to enter an issue directly on the AssignedAccess module -- however, it would seem prudent to - at a minimum -- update the documentation to reflect actually how the module works. If possible, I would recommend to the AssignedAccess module team that they re-examine the structure of this module to more accurately reflect the standard structure for PowerShell modules and the standard interfaces/pipelining that administrators/programmers expect. (e.g. As noted  correctly in the documentation you cannot pipeline input into this function. The function definitions make this clear - but it would seem like a simple fix to allow, for example, the output object of Get-LocalUser as an acceptable input object for this module.)

Thank you! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb59eca8-5436-3f3a-0486-b0876b4e7e20
* Version Independent ID: 974efd9f-ba05-4c9f-123d-2ab740b5dff0
* Content: [Set-AssignedAccess (assignedaccess)](https://docs.microsoft.com/en-us/powershell/module/assignedaccess/set-assignedaccess?view=win10-ps)
* Content Source: [docset/windows/assignedaccess/set-assignedaccess.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/assignedaccess/set-assignedaccess.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by PrinceMarkieD** [comment] 2019-05-14 19:20
Can this be used to specify Win32 apps for Assigned Access?

**Comment by e0i** [comment] 2019-06-20 13:46
@officedocsbot unassign @e0i
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2019-06-25 12:52
Duplicate of https://github.com/MicrosoftDocs/windows-powershell-docs/issues/428 we will close this one.

**Comment by yogkumgit** [comment] 2019-06-25 13:08
@officedocsbot close

**Closed by yogkumgit** 2019-06-25 13:08 UTC
