### ISSUE TITLE
Parameters LockoutDuration, LockoutDurationWindow, MaxPasswordAge, and MinPassword Cannot be Negative

### ISSUE THREAD

**Issue by RichardMueller-8175** [MicrosoftDocs/windows-powershell-docs#1844] opened 2020-03-21 22:29 UTC
The time interval should be in the format (without the string "[-]"):
D.H:M:S.F

The following applies to the documentation for the MaxPasswordAge and MinPasswordAge parameters:
The string "[-] = Specifies a negative time interval" should be removed.

Time values must be between the following values: 0 and 10675199:02:48:05.4775807 (not -10675199:02:48:05.4775808 and 10675199:02:48:05.4775807).

For the MaxPasswordAge parameter, the following example should be removed:

Set the time span to the previous 2 days
MaxPasswordAge "-2"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a75e4d8f-39ac-c2bd-1e75-1bb234d89654
* Version Independent ID: aeb81a2b-eceb-14e3-1d56-cfeb396b2563
* Content: [New-ADFineGrainedPasswordPolicy (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/new-adfinegrainedpasswordpolicy?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/activedirectory/New-ADFineGrainedPasswordPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/winserver2012-ps/activedirectory/New-ADFineGrainedPasswordPolicy.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment] 2020-04-01 00:27
Duplicate of #1842

**Comment by RichardMueller-8175** [comment] 2020-04-01 14:07
#1842 and #1844 are for the same issue, but different documents for different PowerShell AD cmdlets.#1842 applies to Set-ADDefaultDomainPasswordPolicy (activedirectory)

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Set-ADDefaultDomainPasswordPolicy (activedirectory)

<p sourcefile="winserver2012-ps/activedirectory/Set-ADDefaultDomainPasswordPolicy.md" sourcestartlinenumber="1">...



 |

 |

 |

#1844 applies to New-ADFineGrainedPasswordPolicy (activedirectory)

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
New-ADFineGrainedPasswordPolicy (activedirectory)

<p sourcefile="winserver2012-ps/activedirectory/New-ADFineGrainedPasswordPolicy.md" sourcestartlinenumber="1">Th...
 |

 |

 |





    On Tuesday, March 31, 2020, 07:27:57 PM CDT, Onur <notifications@github.com> wrote:  
 
 


Duplicate of #1842

**Comment by e0i** [comment] 2020-04-03 20:08
Thank you for the clarifications, the issues are under investigation.

**Comment by msbemba** [comment] 2020-05-23 22:57
@RichardMueller-8175 Thank you for your feedback. We have made changes to the doc via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1988

Thanks
Sri

**Closed** 2020-06-13 15:24 UTC
