### ISSUE TITLE
Wait-VM's existence not documented

### ISSUE THREAD

**Issue by mattpwhite** [MicrosoftDocs/windows-powershell-docs#240] opened 2018-06-18 19:24 UTC
There is a Wait-VM cmdlet that ships in the Hyper-V module, but does not appear on the online docs and does not have help available from whatever `Update-Help` talks to.  It is covered a bit on this blog post, it would be nice if it had a proper help page.  https://blogs.technet.microsoft.com/virtualization/2016/10/11/waiting-for-vms-to-restart-in-a-complex-configuration-script-with-powershell-direct/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9215b373-6393-6a97-b134-cdd2b7ea4dc6
* Version Independent ID: 54749da2-d4d2-800e-8baa-b2018f32fb82
* Content: [Hyper-V](https://docs.microsoft.com/en-us/powershell/module/hyper-v/?view=win10-ps)
* Content Source: [docset/windows/hyper-v/hyper-v.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/hyper-v.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment] 2019-03-14 20:24
@officedocsbot assign @yogkumgit

**Comment by e0i** [comment] 2019-06-20 13:07
@officedocsbot unassign @e0i

**Comment by get-itips** [comment] 2019-07-05 23:47
Hello @brianlic-msft can you help us with this? thank you!

**Comment by get-itips** [comment] 2019-08-02 20:42
Hello @AndreaBarr can you help us locating the right people to confirm this ? Thank you

**Comment by rrperkin** [comment] 2021-05-24 20:04
Are y'all ever going to document this?

**Comment by AberrantMonk** [comment] 2022-02-13 22:47
Wow- almost 4 years and the only progress made has been the assignees going in circles and a label added.

**Comment by igpit** [comment] 2022-04-26 21:04
ping

**Comment by codaamok** [comment] 2022-10-25 21:12
@officedocsbot assign @e0i

**Comment by ApexxX0** [comment] 2023-01-04 19:56
Can none of the people in this assigning loop really answer this question?

**Comment by jtlarson** [comment] 2023-02-24 00:04
I'd like to see this updated too...

**Comment by ZianAtFirstWatch** [comment] 2023-04-17 22:06
The [link](https://web.archive.org/web/20190323205920/https://blogs.technet.microsoft.com/virtualization/2016/10/11/waiting-for-vms-to-restart-in-a-complex-configuration-script-with-powershell-direct/) has a comment that expresses a desire for a command like Wait-VM but it does not explain what the real Wait-VM command does.

**Comment by schittli** [comment] 2023-05-22 21:14
**What a shame for Microsoft...**

Microsoft calls a lot of things 'docs', which are not worth the name and our apprentices and interns write better docs.

**But there are even Microsoft teams that completely lack the inner motivation** to offer Microsoft customers minimally decent documentation?

**Even when paying customers point out such embarrassing mistakes**, customers are simply ignored. For years.

We can watch how M$ products are less and less worth buying.

Kind regards,
Thomas

**Comment by tiburd** [comment] 2023-06-02 16:25
The content development team reports that they plan to update the Hyper-V module soon and will be prioritizing the Wait-VM cmdlet.

Development work is tracked in an internal system, so I'm closing this issue.

**Comment by mattpwhite** [comment] 2023-06-02 18:14
So why not keep this open until that ships? Is there a planned year of release for that? We're half way to a decade already, if this issue were a human child, it would be entering kindergarten. Should we expect a release before or after this issue reaches high school?

More generally - does Microsoft intend to publish help for new cmdlets or parameters? When I logged this issue, it was a bit of an anomaly - most stuff shipped in Windows inbox modules was documented. That's no longer the case. The overwhelming majority of what was shipped in 2019 or 2022 is not documented. And it's not like there was a great deal added in either of those releases. For instance, go try to find literally anything on the `FailoverClusterSet` module. Updates to the docs for the WMI providers many of those modules use also stopped being updated around that time. The help update mechanism for Windows PowerShell was left broken for years at a time. It seemed like a fairly clear "docs are no longer a thing, this is no one's job now" message to any reasonable observer. 

I realize I'm shouting into the void here (see above - "no one's job"), but figured I'd ask.

**Comment by dstrome** [comment] 2023-06-12 19:10
@mattpwhite and @schittli - thanks very much for your feedback. I understand your frustration and I'm going to forward this thread to our leadership as it's a good example of the pain individuals like yourselves are experiencing.

We're closing this issue because the problem is well understood and the team responsible for the content is tracking the work internally.

Thanks,
David.

**Closed by dstrome** 2023-06-12 19:10 UTC
Labels: doc-enhancement, area-hyper-v
