### ISSUE TITLE
Restoring AD Configuration

### ISSUE THREAD

**Issue by MinutemanHS** [MicrosoftDocs/windows-powershell-docs#214] opened 2018-05-29 16:56 UTC
If you want to restore configuration objects or get configuration objects, which are saved in a different location from user objects, you need to use the -SearchBase option in Get-ADObject. You cannot see the configuration location using ADUC or ADAC. You can see it when you use ADSIEdit or LDP (if you drill down into the Configuration CN). I could not find any PowerShell documentation on this, so I'm sharing here. Here are some examples. Use -WhatIf to see if the correct data will be restored. Use -Confirm to verify each object that will be restored. You may have to run the command more than once since all parent CNs must exist before a child object can be restored and if a child object tries to get restored before any parent container, it won't be restored until you run the command again.

EXAMPLE 1: For reference only. Do NOT run this command as is since it will restore all deleted configuration objects even if they should be deleted. Hence the comment in front.
# Get-ADObject -filter 'isdeleted -eq $true -and name -ne "Deleted Objects"' -includeDeletedObjects -property * -SearchBase "CN=Deleted Objects,CN=Configuration,DC=contoso,DC=com" | Restore-ADObject

EXAMPLE 2: This will only restore deleted configuration objects in a certain date/time range. Helpful if you know when these objects were deleted. You can use other filter options to select the objects to restore.
$date1=$ChangeDate = New-Object DateTime(2018, 05, 09)
$date2=$ChangeDate = New-Object DateTime(2018, 05, 09, 15, 00, 00)
Get-ADObject -filter 'whenChanged -gt $date1 -and whenchanged -lt $date2 -and isdeleted -eq $true -and name -ne "Deleted Objects"' -includeDeletedObjects -property * -SearchBase "CN=Deleted Objects,CN=Configuration,DC=contoso,DC=com" | Restore-ADObject

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1670fd4-0409-fbef-209e-30a705ba4953
* Version Independent ID: 7b5c9df0-15ee-b27e-c5ec-ab522ae57f21
* Content: [Restore-ADObject (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/restore-adobject?view=win10-ps)
* Content Source: [docset/windows/addsadministration/restore-adobject.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/restore-adobject.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment] 2019-03-13 20:41
Duplicate of #213

**Comment by e0i** [comment] 2019-03-13 20:42
@officedocsbot close

**Closed by e0i** 2019-03-13 20:42 UTC
