### ISSUE TITLE
Cmdlet outputs "Status", but output object actually has "State" property

### ISSUE THREAD

**Issue by IanKemp** [MicrosoftDocs/windows-powershell-docs#1720] opened 2020-01-22 11:59 UTC
As the examples on this page show, `Get-IISAppPool` outputs a table that contains a `Status` property. However that property does not exist on the `Microsoft.Web.Administration.ApplicationPool` object returned by the cmdlet:

```powershell
> Get-IISAppPool "DefaultAppPool" |select -expandproperty Status
Select-Object: Property "Status" cannot be found.
```

Looking at the [reference](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.administration.applicationpool) for `Microsoft.Web.Administration.ApplicationPool`, we see that it has a `State` property, and indeed using that works:

```powershell
> Get-IISAppPool "DefaultAppPool" |select -expandproperty State
Started
```

Why the discrepancy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eea2e289-d548-6a5c-76c1-ba5492b10144
* Version Independent ID: bb663769-9975-8a51-096f-7af01034f583
* Content: [Get-IISAppPool (iisadministration)](https://docs.microsoft.com/en-us/powershell/module/iisadministration/Get-IISAppPool?view=win10-ps)
* Content Source: [docset/windows/iisadministration/Get-IISAppPool.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/iisadministration/Get-IISAppPool.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment] 2020-05-16 11:54
@IanKemp Hello Ian,

Thank you for your feedback.

**Format-Table** cmdlet does not always return actual property names as table headers. There are default formats  for a lot of types described in *.format.ps1xml and *.types.ps1xml files. You could find this one here:
[iiscommands.format.ps1xml](https://www.powershellgallery.com/packages/IISAdministration/1.1.0.0/Content/iiscommands.format.ps1xml) 
You will see that _Status_ is mapped to _State_

There is a copy of this file in your WinSxS folder.

Let me know if you have any questions.

**Comment by e0i** [comment] 2020-05-25 16:13
The issue is being closed as it seems to have been answered. Thank you for the feedback.

**Closed** 2020-05-25 16:15 UTC
