### ISSUE TITLE
PptpPorts Parameter missing

### ISSUE THREAD

**Issue by andrewwillett** [MicrosoftDocs/windows-powershell-docs#755] opened 2019-03-13 13:15 UTC
This cmdlet is missing a parameter to configure the maximum number of PPTP Ports (unlike other WAN miniports, minimum 1).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca1f61ad-1367-5a1f-d273-5e56403a1398
* Version Independent ID: 51dc34fc-6aab-5fc4-0b98-0baeee3624f4
* Content: [Set-VpnServerConfiguration (remoteaccess)](https://docs.microsoft.com/en-us/powershell/module/remoteaccess/set-vpnserverconfiguration?view=win10-ps)
* Content Source: [docset/windows/remoteaccess/set-vpnserverconfiguration.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/remoteaccess/set-vpnserverconfiguration.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment] 2019-05-25 01:27
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-08-15 10:28
Hello, @andrewwillett 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by sowjanya365** [comment] 2019-09-11 19:31
Hi @andrewwillett 

Thanks for reaching out!

We've verified and felt that PptpPorts parameter is not associated with this command. Kindly let us know if you find it associated with this command anywhere and missing here in this documentation. It will help to investigate further.

Thank you!

**Comment by e0i** [comment] 2019-09-15 21:03
@andrewwillett 

The issue is being marked as resolved as the problematic behavior couldn't be reproduced.

Feel free to re-open this issue if there is still something you'd like to suggest to improve the document.

Thank you for taking the time to provide feedback and follow-up.

**Closed by e0i** 2019-09-15 21:03 UTC
