### ISSUE TITLE
Set-VpnConnectionProxy : -ExceptionPrefix issue with "*"

### ISSUE THREAD

**Issue by Vestarija** [MicrosoftDocs/windows-powershell-docs#2027] opened 2020-06-23 09:23 UTC
Hi,

@velkovb did a great job giving us the solution to define the syntax of -ExceptionPrefix in this [post](https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1855) 
However a problem persists, it is the syntax for IP addresses as in this example :
`-ExceptionPrefix '205.', '*.microsoft.com' `

In this example `*.microsoft.com` will be well taken into consideration but not `205.` , indeed will be necessary to manually add the asterisk after the `.*`   so that it can work.

**Comment by Vestarija** [comment] 2020-07-29 10:29
Hi @e0i,
Do you have any news?

Thank you

**Comment by Vestarija** [comment] 2020-08-25 18:32
Hi,
Nobody have an idea? Maybe I can get around this problem with a script?

**Comment by Cram0** [comment] 2020-08-27 14:44
Hi @e0i ,

Since you self-assigned this issue, could you please update us on a possible fix ?

I have the exact same needs and i can't find any workaround.

Thanks.

**Comment by e0i** [comment] 2020-08-27 14:46
Thank you for following up. The issue is in the backlog for review.

**Comment by Cram0** [comment] 2020-08-27 17:11
Thanks @e0i.

**Comment by velkovb** [comment] 2020-08-28 11:34
@Vestarija Hi,

Really sad to hear it did not work for you. Last time, I was checking with some public addresses and it seemed to work. Could you give me more details on what you are trying to configure (of course without any sensitive data) ?

**Comment by Vestarija** [comment] 2020-08-28 13:35
Hi @velkovb,

Here is an example of what the problem is : 

![image](https://user-images.githubusercontent.com/51925795/91565441-7fd4fe80-e942-11ea-9b9b-56d55f132a9c.png)

Here is what i should have (which i manually edited without PowerShell) : 

![image](https://user-images.githubusercontent.com/51925795/91565644-d7736a00-e942-11ea-8f3d-dbc52e045d23.png)

Here is the command that i use : 

![image](https://user-images.githubusercontent.com/51925795/91565742-f70a9280-e942-11ea-94bf-c8400147a773.png)
(Error says : "Parameter Incorrect")

Adding the wildcard (\*) character causes that error, but only when it is used as a suffix, but if I type "*.domain.test",  it works fine (which is not what i need at the moment) .

As i've tried many solution : 
    - Adding the escape character before the wildcard ( \\* )
    - Using a list
    - Using only one string with ";" separators inbetween each values
    - Using double quotes
    - Using single quotes

None of them worked,

Thank you in advance.

**Comment by Cram0** [comment] 2020-08-28 13:43
Hi @velkovb,

 As @Vestarija just replied, i have the exact same problem, adding a new value using a wildcard character as a suffix such as "192.168.\*" doesn't work.

Thank you for your attention.

**Comment by velkovb** [comment] 2020-08-31 12:52
@Vestarija @Cram0 ,

Thank you for your patience. It seems something somewhere is validating the input of this command and does not allow an asterisk sign unless it is at the beginning of the string (*.192 would work but it is useless, test.*.lab will not work as well).

When setting the property through PowerShell it goes through WMI which performs this validation, while I can guess the GUI writes directly without this validation. This behaviour is most probably a bug and needs to be escalated.

Was not able to find a way to set this value manually only for VPN proxy settings. I would bet there is some registry setting that can help or configure the proxy via script.

**Comment by Cram0** [comment] 2020-08-31 12:58
@velkovb,

Good thing that we might have found a bug somewhere, I will try and see if i can set the VPN proxy through registry tinkering although it seems over complicated for such a simple thing.

Thank you for your reply, have a great afternoon. :+1:

**Comment by Vestarija** [comment] 2020-09-01 10:57
> @Vestarija @Cram0 ,
> 
> Thank you for your patience. It seems something somewhere is validating the input of this command and does not allow an asterisk sign unless it is at the beginning of the string (_.192 would work but it is useless, test._.lab will not work as well).
> 
> When setting the property through PowerShell it goes through WMI which performs this validation, while I can guess the GUI writes directly without this validation. This behaviour is most probably a bug and needs to be escalated.
> 
> Was not able to find a way to set this value manually only for VPN proxy settings. I would bet there is some registry setting that can help or configure the proxy via script.

It's a shame that powershell can't handle such a basic command. 
I have since worked around the problem by editing the **rasphone.pbk** (VPN interfaces) file by GPO.

**Closed** 2020-09-14 18:38 UTC

**Comment by kyleli666** [comment] 2023-09-30 13:25
I find it's still a problem today in 2023 on Windows 11 😢
