### ISSUE TITLE
Thanks for the cmdlet scripts

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-powershell-docs#1124] opened 2019-06-16 11:44 UTC
After seeing commands  i have created all  troubleshooting  commands 
Ceeate new folder name DiagResult  in C:\ and then  run commands in powershell
But you must enable user account control

$Apps = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Apps"
Invoke-TroubleshootingPack -Pack $Apps -Result "C:\DiagResult"

$Audio = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Audio"
Invoke-TroubleshootingPack -Pack $Audio -Result "C:\DiagResult"

$BITS = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\BITS"
Invoke-TroubleshootingPack -Pack $BITS -Result "C:\DiagResult"

$Bluetooth = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Bluetooth"
Invoke-TroubleshootingPack -Pack $Bluetooth -Result "C:\DiagResult"

$Device = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Device"
Invoke-TroubleshootingPack -Pack $Device -Result "C:\DiagResult"

$DeviceCenter = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\DeviceCenter"
Invoke-TroubleshootingPack -Pack $DeviceCenter -Result "C:\DiagResult"

$IEBrowseWeb = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\IEBrowseWeb"
Invoke-TroubleshootingPack -Pack $IEBrowseWeb -Result "C:\DiagResult"

$IESecurity = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\IESecurity"
Invoke-TroubleshootingPack -Pack $IESecurity -Result "C:\DiagResult"

$Keyboard = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Keyboard"
Invoke-TroubleshootingPack -Pack $Keyboard -Result "C:\DiagResult"

$Networking = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Networking"
Invoke-TroubleshootingPack -Pack $Networking -Result "C:\DiagResult"

$PCW = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\PCW"
Invoke-TroubleshootingPack -Pack $PCW -Result "C:\DiagResult"

$Power = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Power"
Invoke-TroubleshootingPack -Pack $Power -Result "C:\DiagResult"

$Printer = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Printer"
Invoke-TroubleshootingPack -Pack $Printer -Result "C:\DiagResult"

$Search = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Search"
Invoke-TroubleshootingPack -Pack $Search -Result "C:\DiagResult"

$Speech = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Speech"
$SpeInvoke-TroubleshootingPack -Pack $Speech -Result "C:\DiagResult"

$Video = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\Video"
Invoke-TroubleshootingPack -Pack $Video -Result "C:\DiagResult"

$WindowsMediaPlayerConfiguration = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\WindowsMediaPlayerConfiguration"
Invoke-TroubleshootingPack -Pack $WindowsMediaPlayerConfiguration -Result "C:\DiagResult"

$WindowsMediaPlayerMediaLibrary = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\WindowsMediaPlayerMediaLibrary"
Invoke-TroubleshootingPack -Pack $WindowsMediaPlayerMediaLibrary -Result "C:\DiagResult"

$WindowsMediaPlayerPlayDVD = Get-TroubleshootingPack -Path "C:\Windows\Diagnostics\System\WindowsMediaPlayerPlayDVD"
Invoke-TroubleshootingPack -Pack $WindowsMediaPlayerPlayDVD -Result "C:\DiagResult"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a72bf24-d5f7-9020-d6ca-41f750617bd8
* Version Independent ID: 06765ad5-b174-8ab6-dcee-e6a00482902c
* Content: [Invoke-TroubleshootingPack (troubleshootingpack)](https://docs.microsoft.com/en-us/powershell/module/troubleshootingpack/invoke-troubleshootingpack?view=win10-ps)
* Content Source: [docset/windows/troubleshootingpack/invoke-troubleshootingpack.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/troubleshootingpack/invoke-troubleshootingpack.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment] 2019-06-17 11:35
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-06-27 10:35
@RAJU2529 Would you be able to clarify the exact subject of your request? Do the documentation needs to be updated? Note that the issues section of this repository is intended for product documentation issues only. Thanks.

**Comment by RAJU2529** [comment] 2019-06-27 10:53
@e0i. No issues in Article. If possible can I add those cmdlets scripts in Article by Pulling request. It will be useful for the reader's. And get all the possible cmdlets in one place

**Comment by e0i** [comment] 2019-07-03 16:05
@RAJU2529 All Open Source contributions are welcome as long as the updates are relevant, and in accordance with contribution guidelines.

The issue is being closed as it does not relate to a documentation problem.

Please do note that the issues section of this repository is intended for product documentation issues only.

Good day.

**Comment by e0i** [comment] 2019-07-03 16:05
@officedocsbot close

**Closed by e0i** 2019-07-03 16:06 UTC
