### ISSUE TITLE
Where do you get these cmdlets from?

### ISSUE THREAD

**Issue by RichMawdsley1** [MicrosoftDocs/windows-powershell-docs#1817] opened 2020-03-12 15:17 UTC
Install-Module RemoteAccess doesn't return anything, and there are no packages in Powershell Gallery that reference it's name.  Where are you supposed to get these from??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 898d597d-1791-c75f-eee4-040ee7782bd0
* Version Independent ID: f94f978d-8758-64d5-a474-a5f5274069aa
* Content: [RemoteAccess](https://docs.microsoft.com/en-us/powershell/module/remoteaccess/?view=win10-ps#feedback)
* Content Source: [docset/windows/remoteaccess/RemoteAccess.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/remoteaccess/RemoteAccess.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by GilKirkpatrick** [comment] 2020-04-29 00:10
You install them as an additional Windows feature:
Install-WindowsFeature RSAT-RemoteAccess-PowerShell

**Comment by e0i** [comment] 2020-05-06 22:12
It seems that the question has been answered by the community,  and thus the issue is being marked as resolved. 

Thank you.

**Closed by e0i** 2020-05-06 22:12 UTC
