### ISSUE TITLE
examples switched

### ISSUE THREAD

**Issue by ivdlinden** [MicrosoftDocs/windows-powershell-docs#1164] opened 2019-07-08 09:21 UTC
examples 1 and 2 are switched !!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a68cbbe-49f9-58ad-c419-78841128daa7
* Version Independent ID: aa6843d9-05cd-63df-cfb4-b3d8f3289e30
* Content: [Publish-AppvClientPackage (appvclient)](https://docs.microsoft.com/en-us/powershell/module/appvclient/publish-appvclientpackage?view=win10-ps)
* Content Source: [docset/windows/appvclient/publish-appvclientpackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appvclient/publish-appvclientpackage.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment] 2019-07-08 14:28
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-08-15 10:28
Hello, @ivdlinden 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by sowjanya365** [comment] 2019-09-11 16:47
Hi @ivdlinden 

Thanks for reaching out!

We've verified the document and we feel that examples are placed very well. First one shows "Publishing a version of a package to all users" and second one shows "Publish a version of a package to a user". Do you still find any issue? Please elaborate more. Thank you!

**Comment by e0i** [comment] 2019-09-15 21:01
@ivdlinden 

The issue is being marked as resolved as the problematic behavior couldn't be reproduced.

Feel free to re-open this issue if there is still something you'd like to suggest to improve the document.

Thank you for taking the time to provide feedback and follow-up.

**Closed by e0i** 2019-09-15 21:01 UTC
