### ISSUE TITLE
No documentation found for "New-SmbGlobalMapping" Powershell cmdlet

### ISSUE THREAD

**Issue by javester** [MicrosoftDocs/windows-powershell-docs#2247] opened 2020-12-19 02:14 UTC
I can't find any documentation on this cmdlet published.

**Comment by doctordns** [comment] 2021-01-02 11:21
Is this a broad duplicate of #1978? 

A related issue is that there seems no online help for this module

```console
PS C:\Foo> get-help New-SmbGlobalMapping -Online
Get-Help: The online version of this Help topic cannot be displayed because the Internet address (URI) of the Help topic is not specified in the command code or in the help file for the command.
```
If you look at the manifest for the SmbShare module - it shows the Help URL as  http://go.microsoft.com/fwlink/?linki390827 which gives a 404.

With all that being said, I suspect this module is a Microsoft proprietary one and can not be changed without the storage product team decide to make the change.

**Comment by e0i** [comment] 2021-01-08 11:16
This is a known issue with the updatable help pipeline that affects the `Get-Help` and `Update-Help` commands.

There are ongoing efforts to rework the publishing engine. Once matured, failures to update modules are also going to be addressed. Internal sources inform us, the independent collaborators that it is going to take a lot of work.

This ticket is being left open for tracking the status of the progress.w

Thank you.

**Comment by e0i** [comment] 2021-04-28 20:27
Update: The PowerShell modules and their corresponding documentation are still being updated. Since each module needs to be handled one by one, this is going to take a while. There is a workaround for one module that might be of help with other modules as well.

See the workaround:  https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module-in-windows-powershell-5-1/

**Comment by doctordns** [comment] 2021-04-29 15:54
I still do not understand why the module names are case sensitivity?

Seems to me to be a shortcoming in Update-Help?

**Comment by e0i** [comment] 2021-04-29 19:37
Obviously it would be because of the capitalization conventions that appear to be a form of “snake case.”

**Closed** 2021-12-18 14:05 UTC
Labels: docs-experience

**Comment by no-identd** [comment] 2023-03-14 20:51
@SwiftOnSecurity you'll wanna check out #1333 and #3278
