### ISSUE TITLE
Missing descriptions and examples

### ISSUE THREAD

**Issue by JasonG-IT** [MicrosoftDocs/windows-powershell-docs#1036] opened 2019-05-03 14:34 UTC
No descriptions or examples on here or using help in powershell. I'm just trying to make sure I can detect a PPKG by ID.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d30e83b-a8aa-f4de-09a1-6e3d55ba16de
* Version Independent ID: 058b8547-e4a8-17cf-1994-d9fbe6423d16
* Content: [Get-ProvisioningPackage (provisioning)](https://docs.microsoft.com/en-us/powershell/module/provisioning/get-provisioningpackage?view=win10-ps#feedback)
* Content Source: [docset/windows/provisioning/get-provisioningpackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/provisioning/get-provisioningpackage.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment] 2019-05-03 19:32
@JasonG-IT 

The issue is being routed to Windows PowerShell writing team for investigation. You'll be notified with relevant updates as content gets updated.

Thank you for providing feedback.

**Comment by e0i** [comment] 2019-05-03 19:32
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-05-23 21:53
@JasonG-IT 

With the help of your feedback, the issue has been reviewed and an update to the documentation has been published. Thanks for your feedback.

**Comment by e0i** [comment] 2019-05-23 21:54
@officedocsbot close

**Comment by JasonG-IT** [comment] 2019-06-10 22:23
I'm confused on why this was closed. There are still no descriptions of any parameters or examples of any code.

With that said, we were able to work around using any PPKGs at all in our current deployment.

**Comment by e0i** [comment] 2019-11-12 02:11
@JasonG-IT Apologies for the late response. The merged content has been published online. Thank you for the follow-up.

**Closed by e0i** 2019-11-12 02:11 UTC
