### ISSUE TITLE
Missing parameters

### ISSUE THREAD

**Issue by Alex-Brooks** [MicrosoftDocs/windows-powershell-docs#1207] opened 2019-07-27 18:43 UTC
Using Set-MpPreference on the latest version of Windows provides more parameters than are documented here.

The list of parameters missing from this page is:

EnableFileHashComputation
EnableLowCpuPriority
RealTimeScanDirection
CloudExtendedTimeout
CloudBlockLevel
EnableNetworkProtection
EnableControlledFolderAccess
AttackSurfaceReductionRules_Ids
AttackSurfaceReductionRules_Actions

There may be others - I've done my best to cross reference, but please do check yourself.

Thanks for looking into this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbad993c-9f2b-9f51-6438-b56cd913ba1b
* Version Independent ID: cc8d93f2-8837-4169-0fc7-167d0ffca777
* Content: [Set-MpPreference (defender)](https://docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=win10-ps#feedback)
* Content Source: [docset/windows/defender/set-mppreference.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/defender/set-mppreference.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment] 2019-08-15 10:27
Hello, @Alex-Brooks 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by sowjanya365** [comment] 2019-09-12 05:42
Hi @Alex-Brooks 

Thank you for reaching out!

This documentation is compatible with the Windows Server 2016 version. Kindly let us know which version of windows server are you referring to? Thank you!

**Comment by e0i** [comment] 2019-09-15 21:03
@Alex-Brooks 

We are closing this issue as there hasn't been a response from your side regarding the specific version where the issue stems from.

Feel free to re-open this issue with clarifications and we'd be glad to come up with content updates.

Thank you for providing feedback.

**Closed by e0i** 2019-09-15 21:03 UTC

**Comment by HenkPoley** [comment] 2020-05-01 09:23
This issue still exists on Windows 10 1909.

**Comment by HenkPoley** [comment] 2020-05-01 09:49
EnableFileHashComputation is documented a bit here: https://docs.microsoft.com/en-us/windows/client-management/mdm/defender-csp

EnableLowCPUPriority, CloudExtendedTimeout, CloudBlockLevel, EnableNetworkProtection, EnableControlledFolderAccess: https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender

There is some talk about AttackSurfaceReductionRules on that page too.

Maybe as a quick fix link to those documentation anchors ?

**Comment by e0i** [comment] 2020-05-07 23:07
Hello, The existing documentation covers versions up to 2016, and documentation for 2019 hasn't been released yet.
