### ISSUE TITLE
Remember that well-known accounts are language dependent!

### ISSUE THREAD

**Issue by HilleFamke** [MicrosoftDocs/windows-powershell-docs#2121] opened 2020-09-17 14:08 UTC
If you use a well-known account for the parameter AccountName, don't use e.g. "Everyone" or "Administrators". Keep in mind that these strings are language dependent. E.g. on German Windows-Systems you must use "Jeder" or "Administratoren" instead. Otherwise you get an error: "Zuordnungen von Kontennamen und Sicherheitskennungen wurden nicht durchgeführt", "FullyQualifiedErrorId : Windows System Error 1332". To be language independent use the corresponding SID strings to get the account name. The SID string for the well-known account "Everyone" is "S-1-1-0".
You get the well-known account if you call:
$AccountName = (New-Object System.Security.Principal.SecurityIdentifier("S-1-1-0")).Translate([System.Security.Principal.NTAccount]).Value
Greetings from Kiel, Germany

**Comment by e0i** [comment] 2020-09-18 16:50
Duplicate of #2120

**Closed by e0i** 2020-09-18 16:50 UTC
