### ISSUE TITLE
-BitsJob is an array, but no info on how the cmdLet interacts with an array of BitsJob

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/windows-powershell-docs#1052] opened 2019-05-20 12:01 UTC
What's the effect of supplying more than one BitsJob?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c4fb913-db10-2eee-4339-83d22c53ee05
* Version Independent ID: 34f9104c-948a-4fdd-235f-de4099dbd98d
* Content: [Add-BitsFile (bitstransfer)](https://docs.microsoft.com/en-us/powershell/module/bitstransfer/add-bitsfile?view=win10-ps)
* Content Source: [docset/windows/bitstransfer/add-bitsfile.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/bitstransfer/add-bitsfile.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment] 2019-05-20 15:47
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-05-27 21:32
Hello, @Bartolomeus-649 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment] 2019-06-14 18:37
@Bartolomeus-649 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment] 2019-06-14 18:37
@officedocsbot close

**Comment by Bartolomeus-649** [comment] 2019-06-14 20:30
Is the new version public? Because I still can't see an explanation of how it would handle, for example, input of an array of jobs and one file.

**Comment by e0i** [comment] 2019-11-12 02:10
@Bartolomeus-649 Yes, The merged content has been published online. Thank you.

**Closed by e0i** 2019-11-12 02:10 UTC
