### ISSUE TITLE
Can ICMP be stateful or not?

### ISSUE THREAD

**Issue by andoryuu-cloud** [MicrosoftDocs/windows-powershell-docs#1654] opened 2019-12-16 20:57 UTC
Can you add stateful ACL rules (on a Hyper-V Virtual Switch) on the ICMP protocol?
If not, this leaves you to either open ICMP to everyone or close ICMP to everyone including the VM itself.
Neither is secure or practical for such an important and basic functionality (ping).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84e15063-e5c5-3bf1-e4e6-c80dcf234ccd
* Version Independent ID: 46a2fe81-8a1b-a2f0-39f1-3a79d6cc0f1a
* Content: [Add-VMNetworkAdapterExtendedAcl (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/add-vmnetworkadapterextendedacl?view=win10-ps)
* Content Source: [docset/windows/hyper-v/Add-VMNetworkAdapterExtendedAcl.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/hyper-v/Add-VMNetworkAdapterExtendedAcl.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by VLG17** [comment] 2020-03-23 15:16
@andoryuu-cloud Looking at the article you mentioned, there is the posibility to choose ICMP for the "-Protocol" parameter. Is this not what you are looking for?

![image](https://user-images.githubusercontent.com/41186174/77331887-04837700-6d2a-11ea-9f47-f9e6a5cb1c65.png)

**Comment by e0i** [comment] 2020-03-31 08:34
@andoryuu-cloud 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation.

Thanks.

**Comment by andoryuu-cloud** [comment] 2020-04-01 11:23
The the "-Protocol" parameter for ICMP in powershell does not work hence my question.

**Comment by VLG17** [comment] 2020-04-01 13:25
@andoryuu-cloud Are you getting an error, or what are you seeing? Could you provide the complete cmdlet syntax you are using?

**Comment by andoryuu-cloud** [comment] 2020-04-02 11:35
Command:
Add-VMNetworkAdapterExtendedAcl -VMName "5f1521b8-66cb-401d-b23f-4f6e373f28ab" -Action Allow -Direction Outbound -Protocol "ICMP" -Weight 100 -Stateful $True

Error:
Add-VMNetworkAdapterExtendedAcl : The operation failed.
Failed while applying switch port settings 'Ethernet Switch Port Extended ACL Settings' on switch 'Ext_Team1': One or m
ore arguments are invalid (0x80070057).
At line:1 char:1
+ Add-VMNetworkAdapterExtendedAcl -VMName "5f1521b8-66cb-401d-b23f-4f6e ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Add-VMNetworkAdapterExtendedAcl], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.AddVMNetworkAdapterExtendedAcl

It won't even work without the stateful option, you have to type "1" instead of "ICMP" to work.

However, typing "1" instead of "ICMP" won't solve the stateful issue:
Command:
Add-VMNetworkAdapterExtendedAcl -VMName "5f1521b8-66cb-401d-b23f-4f6e373f28ab" -Action Allow -Direction Outbound -Protocol 1 -Weight 100 -Stateful $True

Error:
Add-VMNetworkAdapterExtendedAcl : The operation failed.
Failed while applying switch port settings 'Ethernet Switch Port Extended ACL Settings' on switch 'Ext_Team1': One or more arguments are invalid (0x80070057).
At line:1 char:1
+ Add-VMNetworkAdapterExtendedAcl -VMName "5f1521b8-66cb-401d-b23f-4f6e ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Add-VMNetworkAdapterExtendedAcl], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.AddVMNetworkAdapterExtendedAcl

**Comment by VLG17** [comment] 2020-04-04 08:58
@andoryuu-cloud Could you also try specifying a value for "-RemoteIPAddress"? If you are still getting the same error, i recommend [opening a support ticket](https://support.microsoft.com/en-us/contactus/) to have someone from support look into the error and syntax and see why this is failing. 

Afterwards we will be able to conclude if anything needs to be changed in the article.

**Comment by andoryuu-cloud** [comment] 2020-04-04 11:47
@VLG17 So you're saying I have to pay for a support ticket just so you can fix the article or the issue?

Also, -RemoteIPAddress is an invalid parameter with icmp.

**Comment by VLG17** [comment] 2020-04-05 15:56
@andoryuu-cloud I was not trying to imply that you need to pay to get this fixed. Under the [link](https://support.microsoft.com/en-us/contactus/) I provided, there are multiple options, some of which are free. 

What i can help with is changing something in the documentation. But first we need to understand what needs to be changed. I cannot help with troubleshooting steps in order to isolate the issue, That needs to be handled separately by support. You can leverage the new [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) (in preview).

What i will do in the meantime is reach out to the authors of the article and try to get their insights into this issue.

**Comment by e0i** [comment] 2020-04-05 19:10
@andoryuu-cloud 

The independent contributors could not reproduce the problem in a standardized environment.

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community) would, therefore, be a better channel to discuss this issue because the focus of this repository is content fixes.

Feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.

**Comment by andoryuu-cloud** [comment] 2020-04-05 22:10
@e0i So the independent contributors got the powershell command in question to work?

**Comment by VLG17** [comment] 2020-04-09 08:53
@andoryuu-cloud I've tested with 1 instead of ICMP and it worked (replaced sensitive data with xxxxxxxx ):

PS C:\Windows\system32> Add-VMNetworkAdapterExtendedAcl -VMName "xxxxxxxx" -Action Allow -Direction Outbound -Protocol 1 -Weight 100
PS C:\Windows\system32> Get-VMNetworkAdapterExtendedAcl -VMName xxxxxxxx
 

Direction          : Outbound
Action             : Allow
LocalIPAddress     : ANY
RemoteIPAddress    : ANY
LocalPort          : ANY
RemotePort         : ANY
Protocol           : 1
Weight             : 100
Stateful           : False
IdleSessionTimeout : 0
IsolationID        : 0
ParentAdapter      : VMNetworkAdapter (Name = 'Network Adapter', VMName = xxxxxxxx) [VMId = '35f6a9d3-c293-4f06-92e1- xxxxxxxx ']
IsTemplate         : False
CimSession         : CimSession: .
ComputerName       : xxxxxxxx
IsDeleted          : False

**Comment by andoryuu-cloud** [comment] 2020-04-09 22:46
@VLG17 Thanks for trying it out.
At least now we know that the article needs amending since the command does not take ICMP but instead a "1".

Back to my original query:
The article states that the extended ACLs can be stateful but even swapping "ICMP" with "1" the stateful parameter is not recognized. This either means that there is a bug with the powershell command or the article needs to specify that this is for TCP/UDP only. Could you kindly let us know which one is it?

**Comment by VLG17** [comment] 2020-04-13 10:22
@andoryuu-cloud I'll amend that.

Regarding using the -Stateful parameter with "1" (meaning ICMP), i could also reproduce the issue and error you are seeing I have also tested it for UDP, and it works with -Stateful $true, so the only problem is for 1 (ICMP).

Keeping this in mind, i think we need to ask @e0i to help with this part.

**Comment by e0i** [comment] 2020-04-14 18:49
Closing via #1893

**Comment by andoryuu-cloud** [comment] 2020-04-22 15:37
That's great, however, I'm disappointed that this issue has been masked and nothing else.
At least contact the Windows Server team to fix the issues here:
1.) Make "ICMP" valid in the powershell command instead of having "TCP", "UDP", and "1" ... 
2.) Make ICMP stateful (it's 2020, cmon) ... or update the document stating that the stateful argument can only be done on TCP or UDP.

**Comment by andoryuu-cloud** [comment] 2020-07-15 09:25
Any updates?

**Comment by e0i** [comment] 2020-07-21 09:40
@andoryuu-cloud 

The issue has been closed because the associated article has been updated according to your feedback.

The issues section of this repository is exclusively for documentation problems.

Please consider [sending feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub), or checking with [Microsoft Community](https://answers.microsoft.com/en-us/windows/forum/windows_10) for your feedback.

Thank you.

**Comment by scanum** [comment] 2022-11-07 06:03
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support

**Comment by andoryuu-cloud** [comment] 2023-05-31 15:23
@scanum Can this be checked with the hyper-v team?

**Closed** 2023-06-05 04:32 UTC
Labels: question, area-hyper-v
