### ISSUE TITLE
"At" deletes or not?

### ISSUE THREAD

**Issue by ActualReverend** [MicrosoftDocs/windows-powershell-docs#565] opened 2019-01-30 18:09 UTC
I cannot seem to use "Register-ScheduledTask" with this, if I also include the param"-At" .  Does this imply that using "-At" should delete the scheduled task at a later time/date?  Testing has shown that the script doesn't immediately remove itself, but other pages say that there is a cleaning process that comes around to clean up "run once" tasks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cad6aa9-2504-d30a-9a51-984f52e4f9c8
* Version Independent ID: 84be6419-e750-a16e-70fc-85a3fb0d0569
* Content: [New-ScheduledTaskTrigger (scheduledtasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtasktrigger?view=win10-ps)
* Content Source: [docset/windows/scheduledtasks/new-scheduledtasktrigger.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/scheduledtasks/new-scheduledtasktrigger.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by velkovb** [comment] 2019-05-28 12:47
@ActualReverend Thank you for your constructive feedback. We really appreciate you taking time to improve the content. I am working on the submitted issue, but I am having trouble replicating the problem and understanding it. I had no problem registering a task which has a trigger with the -At parameter. 
Could you provide the example that is failing?
Could you provide reference to the pages describing the cleanup process?

**Comment by ActualReverend** [comment] 2019-05-28 23:53
From what I remember, I would have no problem creating the task for let's say "in 15 min"... but the task would stick around forever.  One server I did this on had a few dozen "run once" scripts that had either failed or succeed (it didn't matter) and were not scheduled to run again, yet stuck around until I manually deleted them.  I was under the impression that after a task was finished, it would (should) remove itself if not scheduled again.  I created the trigger using "-At" with New-ScheduledTaskTrigger, that then was passed to "Register-ScheduledTask."

**Comment by velkovb** [comment] 2019-05-29 05:58
@ActualReverend Hi Bryan, thank you for getting back to me. I know it has been a while and it is hard to remember exactly what the issue was. Unfortunately, I am not aware of any functionality that will automatically cleanup such tasks once they are executed. If you could recall those other pages where you read about this functionality I could do further investigation.

**Comment by e0i** [comment] 2019-06-03 14:46
@ActualReverend 

The issue is being marked as resolved as the problematic behavior couldn't be reproduced.

Feel free to re-open this issue if there is still something you'd like to suggest to improve the document.

Thank you for taking the time to provide feedback and follow-up.

**Comment by e0i** [comment] 2019-06-03 14:46
@officedocsbot close

**Closed by e0i** 2019-06-03 14:46 UTC
