### ISSUE TITLE
set printer color in powershell

### ISSUE THREAD

**Issue by jgeorgebrown** [MicrosoftDocs/windows-powershell-docs#1919] opened 2020-05-01 15:45 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 347ab178-35db-e863-11aa-342d3f354153
* Version Independent ID: 1039a129-0b93-b0a0-5891-8177d616a1b0
* Content: [Set-Printer (printmanagement)](https://docs.microsoft.com/en-us/powershell/module/printmanagement/set-printer?view=winserver2012r2-ps&redirectedfrom=MSDN)
* Content Source: [docset/winserver2012r2-ps/printmanagement/Set-Printer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/printmanagement/Set-Printer.md)
* Product: **powershell**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment] 2020-05-06 12:39
Closing because the issue is missing feedbak.

**Closed by e0i** 2020-05-06 12:39 UTC
