### ISSUE TITLE
This is the preferred usage when running the cmdlet interactively.

### ISSUE THREAD

**Issue by barrypicker** [MicrosoftDocs/windows-powershell-docs#1667] opened 2020-01-01 22:57 UTC
What is the preferred usage?  Using option "-SafeModeAdministratorPassword" or  "cmdlet prompts you to enter and confirm a masked password" (i.e., don't use option "-SafeModeAdministratorPassword" )?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5530d2fd-45fd-6068-9c2a-2b079a7525d1
* Version Independent ID: b129b58f-7ed8-b268-e79b-1ebd804a6a6a
* Content: [Install-ADDSForest (addsdeployment)](https://docs.microsoft.com/en-us/powershell/module/addsdeployment/install-addsforest?view=win10-ps#feedback)
* Content Source: [docset/windows/addsdeployment/Install-ADDSForest.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/addsdeployment/Install-ADDSForest.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment] 2020-05-17 12:41
@barrypicker Hello,

Thanks for your feedback.

I agree that the description is a bit confusing. The recommended usage should be without using the  "-SafeModeAdministratorPassword" because this way you are not specifying the password in plain text but as masked input and you are prompted to confirm it. If you specify it inline with  "-SafeModeAdministratorPassword" and a SecureString you enter it only once and it will be in plain text and you could make a mistake.

**Comment by e0i** [comment] 2020-05-25 16:20
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.

**Closed by e0i** 2020-05-25 16:20 UTC
