### ISSUE TITLE
Parameters LockoutDuration, LockoutDurationWindow, MaxPasswordAge, and MinPassword Cannot be Negative

### ISSUE THREAD

**Issue by RichardMueller-8175** [MicrosoftDocs/windows-powershell-docs#1843] opened 2020-03-21 22:17 UTC
The time interval should be in the format (without the string "[-]"):
D.H:M:S.F

The following applies to the documentation for the MaxPasswordAge and MinPasswordAge parameters:
The string "[-] = Specifies a negative time interval" should be removed.

Time values must be between the following values: 0 and 10675199:02:48:05.4775807 (not -10675199:02:48:05.4775808 and 10675199:02:48:05.4775807).

For the MaxPasswordAge parameter, the following example should be removed:

Set the time span to the previous 2 days
MaxPasswordAge "-2"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d376ba3-2395-ea6c-8ac9-37265255a441
* Version Independent ID: 640602bf-f0e4-2618-c6c6-b4683a099571
* Content: [Set-ADFineGrainedPasswordPolicy (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/set-adfinegrainedpasswordpolicy?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/activedirectory/Set-ADFineGrainedPasswordPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/winserver2012-ps/activedirectory/Set-ADFineGrainedPasswordPolicy.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment] 2020-04-01 00:27
Duplicate of #1842

**Comment by RichardMueller-8175** [comment] 2020-04-01 14:10
#1843 and #1844 are for the same issue, but different documents for different PowerShell AD cmdlets.#1843 applies to Set-ADFineGrainedPasswordPolicy (activedirectory)

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Set-ADFineGrainedPasswordPolicy (activedirectory)

<p sourcefile="winserver2012-ps/activedirectory/Set-ADFineGrainedPasswordPolicy.md" sourcestartlinenumber="1">Th...
 |

 |

 |

#1844 applies to New-ADFineGrainedPasswordPolicy (activedirectory)

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
New-ADFineGrainedPasswordPolicy (activedirectory)

<p sourcefile="winserver2012-ps/activedirectory/New-ADFineGrainedPasswordPolicy.md" sourcestartlinenumber="1">Th...
 |

 |

 |






    On Tuesday, March 31, 2020, 07:28:06 PM CDT, Onur <notifications@github.com> wrote:  
 
 


Closed #1843.

**Comment by e0i** [comment] 2020-04-03 20:08
Thank you for the clarifications, the issues are under investigation.

**Comment by msbemba** [comment] 2020-05-23 22:53
@RichardMueller-8175 Thank you for your feedback. We have modified the document via PR# https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1987

Thanks
Sri

**Closed** 2020-06-13 15:23 UTC
