### ISSUE TITLE
To import the AGPM Module

### ISSUE THREAD

**Issue by LijuV-MSFT** [MicrosoftDocs/windows-powershell-docs#719] opened 2019-02-20 19:57 UTC
The files are found under the Client installation folder. To import, run:
Import-Module -Name "C:\Program Files\Microsoft\AGPM\Client\Microsoft.Agpm\Microsoft.AGPM.psd1"

To get a list of the commands, run:
Get-Command -Module Microsoft.AGPM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9176d150-c0e8-0e54-ce08-8bb181380bc9
* Version Independent ID: 83d595c2-d05a-cad9-1eb0-8655a03f866e
* Content: [AGPM](https://docs.microsoft.com/en-us/powershell/module/agpm/?view=win-mdop2-ps)
* Content Source: [docset/mdop/agpm/agpm.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/mdop/agpm/agpm.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **coreyp**

**Comment by kensel** [comment] 2019-05-08 17:01
Is there a cmdlet to import Controlled GPO from production?  Looking at a script that will import from production Daily and report changed GPOs.

**Comment by SetiGeek** [comment] 2019-05-14 08:34
I created a user voice for this. Actually, there is no way of doing this import
https://windowsserver.uservoice.com/forums/304621-active-directory/suggestions/37640764-agpm-and-powershell-scripting

**Comment by e0i** [comment] 2019-06-18 16:20
Hello, @LijuV-MSFT 

Would you be able to clarify what needs to be updated in the documentation? Is the document misleading? What is missing?

We would like to follow-up with content updates accordingly.

Thank you for providing feedback.

**Comment by LijuV-MSFT** [comment] 2019-06-18 17:38
I recommend updating the content with this pertinent information:

The files are found under the Client installation folder. To import, run:
Import-Module -Name "C:\Program Files\Microsoft\AGPM\Client\Microsoft.Agpm\Microsoft.AGPM.psd1"

To get a list of the commands, run:
Get-Command -Module Microsoft.AGPM

**Comment by MaratMussabekov** [comment] 2019-09-25 11:08
Dear @LijuV-MSFT ,
commands you provided are useful for sure, but they are out of scope of the article.
the article contains references to the articles of the AGPM set of commandlets, not the "How to" instructions for using of PowerShell.
What do you think?

**Comment by e0i** [comment] 2019-10-17 19:05
Hello @LijuV-MSFT,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.

**Closed by e0i** 2019-10-17 19:05 UTC
