### ISSUE TITLE
 no Resolve-DnsName  in the dnsclient

### ISSUE THREAD

**Issue by DDmchk** [MicrosoftDocs/windows-powershell-docs#1088] opened 2019-06-02 08:20 UTC
Why there is no Resolve-DnsName  in the list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d783b08d-bb01-da8f-e49c-7e18aac96e43
* Version Independent ID: eee454be-aacf-d781-ff57-bd9f19c32191
* Content: [DnsClient](https://docs.microsoft.com/en-us/powershell/module/dnsclient/?view=win10-ps#feedback)
* Content Source: [docset/windows/dnsclient/dnsclient.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dnsclient/dnsclient.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment] 2019-06-06 16:57
@officedocsbot assign @e0i

**Comment by e0i** [comment] 2019-06-10 19:32
Hello, @DDmchk 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment] 2019-06-11 20:40
@DDmchk 

In our investigation it has been found that this issue has already been addressed with the following commit,

[[27a4532 ] Added Resolve-DnsName article ](https://github.com/MicrosoftDocs/windows-powershell-docs/commit/27a4532c86157a46ab219c64e132b64b54060efd#diff-e8c4be659ad94eab7d4e3e0dd8295ae3)

We are thus closing this issue since it seems to be resolved. 

It may take a while for changes to go live.

Thank you for taking the time to provide feedback.

**Comment by e0i** [comment] 2019-06-11 20:40
@officedocsbot close

**Closed by e0i** 2019-06-11 20:40 UTC
