### ISSUE TITLE
Missing asterisk?

### ISSUE THREAD

**Issue by mossywell** [MicrosoftDocs/windows-powershell-docs#1198] opened 2019-07-23 08:49 UTC
Should this line:
Note: Windows PowerShell wildcards other than , such as ?, are not supported by the *Filter syntax.
Say this:
Note: Windows PowerShell wildcards other than *, such as ?, are not supported by the *Filter syntax.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a11d541-b67b-d5e4-6ca3-05db321746cd
* Version Independent ID: 3eb1d45a-94e9-239f-613f-19fd837ab24e
* Content: [Get-ADComputer (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/get-adcomputer?view=win10-ps)
* Content Source: [docset/windows/addsadministration/get-adcomputer.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/get-adcomputer.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment] 2019-07-23 23:34
@officedocsbot assign @e0i

**Comment by msbemba** [comment] 2019-08-19 15:46
@mossywell Thank you for your feedback. I dont see the note on the document any more. Either It was removed recently or I'm looking at the wrong document. Can you confirm if the doc is question is  https://docs.microsoft.com/en-us/powershell/module/addsadministration/get-adcomputer?view=win10-ps ?

Thanks
Sri

**Comment by e0i** [comment] 2019-08-20 16:13
@msbemba It seems both links are equivalent.

**Comment by e0i** [comment] 2019-09-04 22:02
@mossywell 

The issue is being closed as we haven't been able to identify the source of error within the referenced documentation. 

Feel free to re-open this issue with further clarifications and we would gladly assess the content for updates.

Thank you for your feedback.

**Closed by e0i** 2019-09-04 22:02 UTC
