### ISSUE TITLE
app firewall rules

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/windows-powershell-docs#414] opened 2018-10-12 21:43 UTC
"[ConfigurableServiceStore] In addition, network isolation rules that are created for Windows Store application containers will appear in this policy store."

This is out of date.  The app related rules are now stored in the registry under  HKLM:\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\RestrictedServices\AppIso\FirewallRules and aren't accessible by get-netfirewallrule.  That area grows without bounds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b3c4b46-6585-2dc2-1ff6-6d8e7b0c3765
* Version Independent ID: 43521c30-86e8-796d-b984-2495f8da71e1
* Content: [Get-NetFirewallRule (netsecurity)](https://docs.microsoft.com/en-us/powershell/module/netsecurity/get-netfirewallrule?view=win10-ps)
* Content Source: [docset/windows/netsecurity/get-netfirewallrule.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/netsecurity/get-netfirewallrule.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment] 2020-01-29 17:51
The issue is being noted for a second attempt to fix. Thank you for feedback.

**Comment by e0i** [comment] 2020-03-31 08:25
Closing via #1820. Thank you.

**Closed by e0i** 2020-03-31 08:25 UTC
